#!/bin/env bash

SCRIPT_PATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
TESTS_PATH="$(dirname "$SCRIPT_PATH")/tests"
# Run from project root (./scripts/test)
nvim -l $TESTS_PATH/minit.lua --minitest
